# Generated by Django 6.0.3 on 2026-03-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='genre',
            name='name_ru',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
