# Generated by Django 6.0.3 on 2026-03-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_genre_name_en_genre_name_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True)),
                ('duration', models.IntegerField()),
                ('genres', models.ManyToManyField(to='main.genre')),
            ],
        ),
    ]
